apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-helloworld
  namespace: helloworld
spec:
  type: LoadBalancer
  selector:
    app: helloworld
  ports:
    - port: 80         # IP_EXTERNO:80 -> Endereco p/ acessar externamente 
      targetPort: 8080   # Porta que o app escuta internamente