apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-helloworld
  namespace: helloworld
spec:
  type: LoadBalancer
  selector:
    app: helloworld
  ports:
    - port: 8079         # IP_EXTERNO:8079 -> Endereco p/ acessar externamente 
      targetPort: 8080   # Porta que o app escuta internamente
      nodePort: 30080  # Nao faco ideia se precisa